/*
  # Create responses table for MCQ exam

  1. New Tables
    - `responses` - Stores student exam responses
      - `id` (bigint, primary key)
      - `created_at` (timestamptz, default now())
      - `fullName` (text, not null)
      - `schoolName` (text, not null)
      - `answers` (jsonb, not null) - JSON object with question id as key and answer as value
      - `score` (integer, not null) - Number of correct answers
      - `totalQuestions` (integer, not null) - Total number of questions
      - `timeSpent` (integer, not null) - Time spent in seconds
  
  2. Security
    - Enable RLS on `responses` table
    - Add policy for authenticated users to read all responses
    - Add policy for authenticated users to insert responses
*/

-- Create responses table
CREATE TABLE IF NOT EXISTS responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  "fullName" text NOT NULL,
  "schoolName" text NOT NULL,
  answers jsonb NOT NULL,
  score integer NOT NULL,
  "totalQuestions" integer NOT NULL,
  "timeSpent" integer NOT NULL
);

-- Enable Row Level Security
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow authenticated users to read responses"
  ON responses
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow anyone to insert responses"
  ON responses
  FOR INSERT
  TO anon
  WITH CHECK (true);